Port to NeoForge 1.21

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -45,19 +45,16 @@ jobs:
         cache-read-only: ${{ github.ref != 'refs/heads/master' && !contains(github.ref, 'neoforge') }}
 
     - name: Compile Java code
-      run: ./gradlew remapJar --stacktrace --warning-mode=fail
+      run: ./gradlew jar --stacktrace --warning-mode=fail
+
+    - name: Validate Java code style
+      run: ./gradlew spotlessJavaCheck || (echo "::error::Java code style validation failed! To fix, run 'Clean Up' and then 'Format' in Eclipse, or './gradlew spotlessApply' in the terminal." && exit 1)
 
     - name: Validate JSON files
       run: ./gradlew spotlessJsonCheck || (echo "::error::JSON validation failed! Run './gradlew spotlessApply' to fix style issues, or check the full error message for syntax errors." && exit 1)
 
-    - name: Validate Java code style
-      run: ./gradlew spotlessCheck || (echo "::error::Java code style validation failed! To fix, run 'Clean Up' and then 'Format' in Eclipse, or './gradlew spotlessApply' in the terminal." && exit 1)
-
     - name: Run unit tests
       run: ./gradlew test --stacktrace --warning-mode=fail
-
-    - name: Validate access widener
-      run: ./gradlew validateAccessWidener --stacktrace --warning-mode=fail
 
     - name: Build
       run: ./gradlew build --stacktrace --warning-mode=fail
